### PR TITLE
Corrections to the optical prop files of the new composition for AGN dust

### PR DESCRIPTION
**Pull request by oura71**
**Description**
The files of optical properties of Periclase and Porous Alumina calculated considering spherical grains were replaced by files with optical properties considering grains described by a continuous distribution of elliposids. For the Olivine file, only information was added in the commented section, where it is specified that the grains are spherical.

### CODE REVIEW

**Comment by petercamps** [comment]
1. I will also need the updated resource files in the same format as before; you can attach them here if not too large or send them to me through other means.
2. Should we wait with this update until you have resolved the Periclase issue with your initial tests (see email communication to @mbaes)?

**Comment by oura71** [comment]
> 1. I will also need the updated resource files in the same format as before; you can attach them here if not too large or send them to me through other means.
> 2. Should we wait with this update until you have resolved the Periclase issue with your initial tests (see email communication to @mbaes)?

The problem with Periclase is related with the changes I made with the files. Just let me do some tests to confirm that and I will attach here the updated resource files.

**Comment by oura71** [comment]
Well, I made the tests and everything is okay. I attach here the updated resources files. Thanks!
[input_skirt_optical_properties_olivine_rangesizes.txt](https://github.com/SKIRT/SKIRT9/files/11511079/input_skirt_optical_properties_olivine_rangesizes.txt)
[input_skirt_optical_poperties_CDE_periclase_rangesizes.txt](https://github.com/SKIRT/SKIRT9/files/11511080/input_skirt_optical_poperties_CDE_periclase_rangesizes.txt)
[input_skirt_optical_properties_CDE_PoAL_LD_combination_rangesizes.txt](https://github.com/SKIRT/SKIRT9/files/11511081/input_skirt_optical_properties_CDE_PoAL_LD_combination_rangesizes.txt)

**Comment by oura71** [comment]
> Well, I made the tests and everything is okay. I attach here the updated resources files. Thanks! [input_skirt_optical_properties_olivine_rangesizes.txt](https://github.com/SKIRT/SKIRT9/files/11511079/input_skirt_optical_properties_olivine_rangesizes.txt) [input_skirt_optical_poperties_CDE_periclase_rangesizes.txt](https://github.com/SKIRT/SKIRT9/files/11511080/input_skirt_optical_poperties_CDE_periclase_rangesizes.txt) [input_skirt_optical_properties_CDE_PoAL_LD_combination_rangesizes.txt](https://github.com/SKIRT/SKIRT9/files/11511081/input_skirt_optical_properties_CDE_PoAL_LD_combination_rangesizes.txt)

I don't remember if this is the format I sent you before. Maybe you also need the .stab files? please let me know.

**Pull request merged**
